version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
    ports:
      - "5440:5432"
    restart: always
  postgres-test:
    image: postgres
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
    ports:
      - "6040:5432"
    restart: always
  poc-handler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_DB: host.docker.internal
    environment:
    links:
      - postgres
      - postgres-test
    depends_on:
      - postgres-test
      - postgres
    ports:
      - "9192:9192"
